name: we_budget
description: "A shared budget tracking app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  envied: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^3.1.0
  go_router: ^16.0.0
  google_sign_in: ^7.1.1
  supabase_flutter: ^2.9.1
  riverpod_annotation: ^2.6.1
  gap: ^3.0.1
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
